### ISSUE TITLE
广州大学ipv4地址获取错误。

### ISSUE THREAD

**Issue by YZcrazy970** [ysc3839/openwrt-minieap#1]
ipv4 获取错误，但是能通过验证。

**Comment by ysc3839** [comment]
请给出详细日志。

**Comment by YZcrazy970** [comment]
非常感谢你的及时回复。minieap日志
Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [I]Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): RJv3 for MiniEAP 0.92.1Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): V3 校验算法来自 hyrathb@GitHubMon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): Hamster Tian, 2016Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619):Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [I] ========================Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [I] MiniEAP 0.92.1已启动Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [I] 正在查找认证服务器Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [E] IPv4 地址获取错误Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [I] 正在回应用户名请求Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [E] IPv4 地址获取错误Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [I] 正在回应密码请求Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [E] IPv4 地址获取错误Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [I] 计费通知：Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [I] 您当前使用的服务为internet;Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): 账户余额为60.00元;Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): 计费策略为30元包月;Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): 您当前使用的接入控制为default;Mon Jun 10 18:34:59 2019 daemon.notice netifd: wan (3619): [I] 认证成功Mon Jun 10 18:34:59 2019 daemon.notice netifd: Interface 'wan' is now up
